#Try with resources

Until the release of Java 6, it was necessary to close all open connections in try-catch blocks with *close()* method. That is something that is often overlooked.
See below some of the disavantages of not using try-with-resources:

## Before try-with-resources

```
public class AlunoDAO {

    private static final String SQL_ALUNOS_POR_TURMA = 
            "SELECT id, nome, telefone FROM alunos WHERE id_turma = ?";

    public static void localizarAlunos(String turma) throws ConexaoFalhouException {
        Connection c = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            c = Conexao.obter();
            ps = c.prepareStatement(SQL_ALUNOS_POR_TURMA);
            ps.setString(1, turma);
            rs = ps.executeQuery();

            List<Aluno> alunos = new ArrayList<Aluno>();
            while (rs.next()) {
                Aluno a = new Aluno();
                a.setInt(rs.getInt(1));
                a.setNome(rs.getString(2));
                a.setTelefone(rs.getString(3));
                alunos.add(a);
            }

            return alunos;
        } catch (SQLException e) {
            throw new ConexaoFalhouException(e);
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (c != null) c.close();
            } catch (SQLException e) {
                throw new ConexaoFalhouException(e);
            }
        }
    }
}
     
```

>
* The developer always have to remember of call *close()* method mannualy.
* If the developer don't use the *try-finally*, with the *close()*, the resource will still be open if the code throws an exception.
* If the developer forget the *ifs* in the *finally* block, he can get an *NullPointerException*.
* If of of the *close()* methods of the *finally* block throws an exception, the others won't be properly closed.
* If one of the *close()* methods of *finally* block throws an exception, that exception will be throwed and will hide any other exception throwed on the try block.

## Using try-with-resources

```
public class AlunoDAO {

    private static final String SQL_ALUNOS_POR_TURMA = 
            "SELECT id, nome, telefone FROM alunos WHERE id_turma = ?";

    public static void localizarAlunos(String turma) throws ConexaoFalhouException {
        try (
            Connection c = Conexao.obter();
            PreparedStatement ps = c.prepareStatement(SQL_ALUNOS_POR_TURMA);
        ) {
            ps.setString(1, turma);
            try (ResultSet rs = ps.executeQuery()) {

                List<Aluno> alunos = new ArrayList<>();
                while (rs.next()) {
                    Aluno a = new Aluno();
                    a.setInt(rs.getInt(1));
                    a.setNome(rs.getString(2));
                    a.setTelefone(rs.getString(3));
                    alunos.add(a);
                }

                return alunos;
            }
        } catch (SQLException e) {
            throw new ConexaoFalhouException(e);
        }
    }
}
```

Using try-with-resources it is no longer necessary use a *finally* block and not even call the *close()* method.

### References

* [Stackoverflow reference: #1](https://pt.stackoverflow.com/questions/172909/como-funciona-o-try-with-resources)
